tutorial4/myproject/models.py
# MODELS.PY
from myproject import db 


class Puppy(db.Model):

    __tablename__ = 'puppies'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    owner = db.relationship('Owner', backref='puppies', uselist=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f"Puppy name is {self.name} and owner name is {self.owner.name}"
        else:
            return f"Puppy name is {self.name} and has no owner yet"


class Owner(db.Model):

    __tablename__ = "Owner"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    puppy_id = db.Column(db.Integer, db.ForeignKey('puppies.id'))

    def __init__(self, name, puppy_id):
        self.name = name
        self.puppy_id = puppy_id

tutorial4/myproject/owner/forms.py
# forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField


class AddForm(FlaskForm):
    name = StringField('Name of the owner')
    id = IntegerField('Puppy id')
    submit = SubmitField('Add Owner')

tutorial4/myproject/puppies/forms.py
# forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField


class AddForm(FlaskForm):
    name = StringField('Name of the puppy : ')
    submit = SubmitField('Add Puppy')


class DelForm(FlaskForm):
    id = IntegerField('Id no of the puppy to remove : ')
    submit = SubmitField('Remove Puppy')

tutorial4/myproject/__init__.py
# __init.py

import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)
app.config['SECRET_KEY'] = 'mysecretkey'

##########################################
######### SQL DATABASE SESSION ###########
##########################################

basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
Migrate(app,db)

from myproject.puppies.views import puppies_blueprints
from myproject.owner.views import owners_blueprints

app.register_blueprint(owners_blueprints, url_prefix = '/owners')
app.register_blueprint(puppies_blueprints, url_prefix = '/puppies')

tutorial4/myproject/owner/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Owner
from myproject.owner.forms import AddForm

owners_blueprints = Blueprint('owners', __name__, template_folder='templates/owner')

@owners_blueprints.route('/add', methods = ['POST', 'GET'])
def add():
    form = AddForm()
    if form.validate_on_submit():
        name = form.name.data
        id = form.id.data
        new_owner = Owner(name, id)
        db.session.add(new_owner)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template('add_owner.html', form=form)

tutorial4/myproject/puppies/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.models import Puppy
from myproject.puppies.forms import AddForm, DelForm

puppies_blueprints = Blueprint('puppies', __name__, template_folder='templates/puppies')


@puppies_blueprints.route('/add', methods=['GET', 'POST'])
def add():

    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        new_pup = Puppy(name)
        db.session.add(new_pup)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template('add.html', form=form)

@puppies_blueprints.route('/list', methods = ['GET', 'POST'])
def list():

    puppies = Puppy.query.all()
    return render_template('list.html', puppies=puppies)


@puppies_blueprints.route('/delete', methods=['GET', 'POST'])
def delete():
    form = DelForm()
    if form.validate_on_submit():
        id = form.id.data
        del_pup = Puppy.query.get(id)
        db.session.delete(del_pup)
        db.session.commit()
        return redirect(url_for('puppies.list'))
    return render_template('delete.html', form=form)

tutorial4/myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</head>

<body class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
            <a class="navbar-brand nav-item nav-link" href="{{url_for('index')}}">Home</a>
            <a class="nav-item nav-link" href="{{url_for('puppies.list')}}">List of pups</a>
            <a class="nav-item nav-link" href="{{url_for('puppies.add')}}">Add pup</a>
            <a class="nav-item nav-link" href="{{url_for('puppies.delete')}}">Delete</a>
            <a class="nav-item nav-link" href="{{url_for('owners.add')}}">Add Owner</a>
        </div>
    </nav>

    {% block content %}

    {% endblock %}

</body>

</html>

tutorial4/myproject/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="mt-3">
    Welcome
</h1>
{% endblock %}